apiVersion: benchmarking.taikun.cloud/v1
kind: PVCBenchmark
metadata:
  name: pvc-bench-om
  namespace: pvc-bench-operator-system
spec:
  pvc:
    size: 20Gi        # pvc size for every pod
    accessMode: ReadWriteOnce
  test:
    tool: fio
    duration: "120s"   # duration of test
    parameters:
      rw: write       # write, read, randread, randwrite, randrw, rw
      bs: 4k          # 4k, 16k, 1m
      size: 10Gi       # size of test file
      ioengine: libaio
      direct: "1"     # disables filesystem caching for a more direct test of the storage
      buffered: "0"   # enables filesystem caching if you want to test the effects of cache
      invalidate: "1" # ensures that the cache is invalidated before starting the test
      numjobs: "1"    # how many jobs run in parallel in every pod
      iodepth: "1"    # number of I/O operations queued at once 
      ramp_time: "10"
  scale:
      pvc_count: 20
