apiVersion: benchmarking.taikun.cloud/v1
kind: PVCBenchmark
metadata:
  name: randrw-multi
  namespace: pvc-bench-operator-system
spec:
  pvc:
    size: 10Gi
    accessMode: ReadWriteOnce
  scale:
    pvc_count: 5
  test:
    duration: "60s"
    parameters:
      rw: randrw
      bs: 4k
      size: 1Gi
      ioengine: libaio
      direct: "1"
    tool: fio
